---
apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podinfo-subscription
  namespace: mpas-podinfo-application
spec:
  component: ocm.software/mpas/podinfo
  destination:
    secretRef:
      name: github-access
    url: ghcr.io/souleb
  interval: 5m0s
  semver: v1.0.3
  source:
    secretRef:
      name: github-access
    url: ghcr.io/open-component-model/mpas
