apiVersion: mpas.ocm.software/v1alpha1
kind: Target
metadata:
  name: podinfo-kubernetes-target
  namespace: mpas-podinfo-application
  labels:
    target.mpas.ocm.software/ingress-enabled: "true" # This label is defined by the component that will use it to select an appropriate target to deploy to.
spec:
  type: kubernetes
  access:
    targetNamespace: podinfo
  serviceAccountName: podinfo-sa
  selector:
    matchLabels
      mpas.ocm.software/target-selector: podinfo-kubernetes-target
